### ISSUE TITLE
Updated to minimum 2.7 is a big issue!

### ISSUE THREAD

**Issue by rbaarsma** [lexik/LexikTranslationBundle#163]
We have a big production application and are using your bundle, but our application can not be quickly updated to symfony 2.7 and we don't have time to invest in it now. Also another bundle requires a maximum version of 2.6, which puts us in a bind. Is there a way to lower this requirement? We are currently using symfony 2.4.10

**Comment by shakaran** [comment]
As you can see in https://packagist.org/packages/lexik/translation-bundle#v2.1.5 you can use version 2.1.5 of this bundle that still contains the minimum version Symfony 2.3

So just install with:

    $ composer.phar require lexik/translation-bundle 2.1.5

**Comment by Pierstoval** [comment]
I also think it's a big issue.
Creating a v3 for 2.7+ is better just because of the fact that 2.3 will die only in may 2016 according to the roadmap, and in 2017 for security fixes. I'd recommend to use 2 branches of the application : 2.x for SF2.3+ and 3.x for SF2.7+ (or 2.8+ if you prefer)
We at work have 2 applications still in SF2.3 that need your bundle, and it seems we won't be able to update to the next version because of this 2.7 dependency. And upgrading from 2.3 to 2.7 costs money our clients may not have yet (and they only consider about a working app, they don't care of any technical update like that, most of the time).

**Comment by cedric-g** [comment]
All `2.x` tags are compatible with SF 2.3, and yes future versions will be tagged as `3.x` (I've already changed the master branch alias to 3.x.x). 
So if you don't want to update your app you can keep using the `2.1.5` version. I've changed the minimum SF version to 2.7 because some new upcoming features will rely on the new profiler data collector that collect messages.

**Comment by Pierstoval** [comment]
At least for security/bug fixes, it could be good to keep a `2.1` branch which would keep BC for Symfony <2.7 and still receive some bugs, but for this, we should find bugs first :smile: 
 
By the way, I'm starting to use your bundle conjointed with `EasyAdminBundle`, I'm gonna test the implementation in the next months on an SF2.3 app (which will be migrated to 2.7 or 2.8 depending on migration date)

**Comment by Rvanlaak** [comment]
The reason for bumping the requirements to `2.7` is because we're working on an integration with the new profiler translation datacollector features.

You can take a look at branch [`list_missing_translations`](https://github.com/lexik/LexikTranslationBundle/tree/list_missing_translations) for  that, and https://github.com/lexik/LexikTranslationBundle/issues/165 for more info.
