### ISSUE TITLE
Symfony 4 support?

### ISSUE THREAD

**Issue by amitlimbadia** [lexik/LexikTranslationBundle#300]
Hey

are you going to provide symfony 4 support? currently it requires symfony-framework bundle 3.0, which is not matching with symfony 4.

**Comment by FabulousCo** [comment]
+1

I get the following issues when checking my deprecations to prepare my project migration to Symfony 4.0:

`Auto-registration of the command "Lexik\Bundle\TranslationBundle\Command\ImportTranslationsCommand" is deprecated since Symfony 3.4 and won't be supported in 4.0. Use PSR-4 based service discovery instead`

`Auto-registration of the command "Lexik\Bundle\TranslationBundle\Command\ExportTranslationsCommand" is deprecated since Symfony 3.4 and won't be supported in 4.0. Use PSR-4 based service discovery instead`

**Comment by spike31** [comment]
Search on PR before comments. 
Thx

https://github.com/lexik/LexikTranslationBundle/pull/294
