### ISSUE TITLE
You have requested a non-existent parameter "kernel.project_dir"

### ISSUE THREAD

**Issue by jayesbe** [lexik/LexikTranslationBundle#321]
Symfony 2.8 LTS

- Updating lexik/translation-bundle (v4.0.9 => v4.0.10): Downloading (100%)  

  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]                                                                            
  You have requested a non-existent parameter "kernel.project_dir". Did you mean one of these: "kernel.root_dir", "kernel.cache_dir", "kernel.logs_dir"?

I guess at some point older versions of symfony won't be supported.. is this one of those times?

**Comment by SanderVerkuil** [comment]
This happens in the [LexikTranslationExtension#L143](https://github.com/lexik/LexikTranslationBundle/blob/4825bc5b245e38306c96024cbb906915914888a8/DependencyInjection/LexikTranslationExtension.php#L143), introduced in 4825bc5b245e38306c96024cbb906915914888a8.

This is indeed a backwards incompatible change, because symfony projects prior to 3.3 didn't have the %kernel.project_dir% parameter.

This might be worked around by either introducing a custom parameter in your own `parameters.yml`, or this project might check for the existence of the `kernel.project_dir` parameter.
