### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by xSlOom** [lexik/LexikTranslationBundle#422]
Hi,

I have a few questions.

- Is it possible to turn off the "delete" translation icon ?
- How to hide some columns automatically ?

The doc is pretty uncomplete imo.

Thank you

**Comment by bartmcleod** [comment]
@xSlOom Interesting questions and also very old by now. I don't have the answers, although I would say you would have to create a PR for each of the features you are asking about, as I have not come across anything like that so far.

I am closing this, because the question is old and you can open a PR if you would still like to see this added as a feature.
